### PR TITLE
Added direct route linking capability

### PR DESCRIPTION
**Pull request by Sp3EdeR**

### CODE REVIEW

**Review by nbali — APPROVED** [review]

**Comment by nbali** [comment]
@Sp3EdeR  this still won't survive a rename, right?

**Comment by Sp3EdeR** [comment]
@nbali, it uses the kml file's names as unique identifiers. (The CR enforces the naming scheme.) So if we change any file's name, the links will break (as in - it will just stay on the main page without faults). But I assume that if we rename a road, it will probably be something different anyway.

**Comment by nbali** [comment]
@Sp3EdeR So I got it right, okay. Then it will have to be handled only if that happens. BTW the links on the left tree show `#menuXX`, but after clicking them the proper `#filename` in the address bar. Was your aim to modify those URLs too?
image
vs
image

**Comment by Sp3EdeR** [comment]
> @Sp3EdeR So I got it right, okay. Then it will have to be handled only if that happens. BTW the links on the left tree show `#menuXX`, but after clicking them the proper `#filename` in the address bar. Was your aim to modify those URLs too?

No, the menu uses a Bootstrap feature, which uses those fragment links for the menu animation. That is how it works. I don't want to modify that behaviour.

**Pull request merged**
