### PR TITLE
Moved more localization-related code to the html file

### PR DESCRIPTION
**Pull request by Sp3EdeR**
This makes it easier to reuse huroutes.js for sites in a different language.

Notes for reviewer:
* https://kmlviewer.nsspot.net/ can be used to open KML files online.
* https://sp3eder.github.io/huroutes/linkmaker.html can be used to decode location marker URLs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Sp3EdeR/huroutes/165)

### CODE REVIEW

**Review by nbali — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Sp3EdeR/huroutes/165)* status: all files reviewed, 3 unresolved discussions (waiting on @miklospuspan and @Sp3EdeR)

*[a discussion](https://reviewable.io/reviews/Sp3EdeR/huroutes/165#-NZvbVe36127GsfobPRH:-NZvbVe4BNYoFnm3U8Da:bpcisvi) (no related file):*
If I pick 'hungarian language' + 'műhold' + 'turistautak' at https://sp3eder.github.io/huroutes/pr/pr-165/ I get the tourist routes twice as the 'műhold' already has them (try toggle it on-off to see it easily) - although this is how the main branch behaves as well, I'm not sure this was intentional or not

___
___
*[`index.html` line 80 at r1](https://reviewable.io/reviews/Sp3EdeR/huroutes/165#-NZvXnB41XT2NJp6qirI:-NZvXnB41XT2NJp6qirJ:bj0j7ie) ([raw file](https://github.com/Sp3EdeR/huroutes/blob/e3d07df3ce9410d90a7dae64b8b25d8906cafc54/index.html#L80)):*
> ```HTML
>         'Dark': 'Sötét',
>         'Dark with bright map': 'Sötét, világos térképpel'
>       },
> ```

I only have a slight complaint about using the english version as keys as it will require changing them at multiple places even if just a character change in the english version
___
*[`index.html` line 98 at r1](https://reviewable.io/reviews/Sp3EdeR/huroutes/165#-NZvb0UHAjXmBI4I6k8C:-NZvb0UHAjXmBI4I6k8D:b-7gr0ba) ([raw file](https://github.com/Sp3EdeR/huroutes/blob/e3d07df3ce9410d90a7dae64b8b25d8906cafc54/index.html#L98)):*
> ```HTML
>     // Hungarian map types
>     huroutes.opt.map.overlays['Turistautak'] = L.tileLayer('https://{s}.tile.openstreetmap.hu/tt/{z}/{x}/{y}.png', {attribution:'&copy; turistautak.hu',minZoom:5,maxZoom: 18,zIndex:100,className: 'overlay-turistautak'});
>     huroutes.opt.map.tileOverlays['Sattelite'] = L.tileLayer('https://map.turistautak.hu/tiles/lines/{z}/{x}/{y}.png', {attribution:'&copy; turistautak.hu',minZoom:5,maxZoom: 18,zIndex:10,className: 'overlay-satteliteroads'});
> ```

I get that it was moved because it's a Hungarian overlay, but how come this requires the english name as the key, but the one above requires the localized name as key?
___
*[`res/huroutes.css` line 441 at r1](https://reviewable.io/reviews/Sp3EdeR/huroutes/165#-NZvPjSo8BSYZBVSm7n4:-NZvPjSo8BSYZBVSm7n5:b-xkxb7b) ([raw file](https://github.com/Sp3EdeR/huroutes/blob/17aeb7a5c005578c15da88c7da629c3b54d69319/res/huroutes.css#L441)):*
> ```CSS
> 
> /* Makes the sattelite view's roads translucent */
> .overlay-satteliteroads {
> ```

fyi you wrote sattelite instead of satellite consistently
___
*[`res/huroutes.js` line 1143 at r1](https://reviewable.io/reviews/Sp3EdeR/huroutes/165#-NZvX5tY6g1l9Rg0navQ:-NZvX5tY6g1l9Rg0navR:b-vc6my) ([raw file](https://github.com/Sp3EdeR/huroutes/blob/e3d07df3ce9410d90a7dae64b8b25d8906cafc54/res/huroutes.js#L1143)):*
> ```JavaScript
>     if (localStorage.mapstyle && !(localStorage.mapstyle in huroutes.opt.map.tiles))
>         localStorage.mapstyle = convert(langDict.map, localStorage.mapstyle);
>     if (localStorage.overlays)
> ```

why don't you omit the conversion here if it's in huroutes.opt.... already like you do with the 2 other?

**Review by nbali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Sp3EdeR/huroutes/165)* status: all files reviewed, 4 unresolved discussions (waiting on @miklospuspan and @Sp3EdeR)

___
*[`index.html` line 76 at r1](https://reviewable.io/reviews/Sp3EdeR/huroutes/165#-NZvdgTG1XbZQwdDKrIl:-NZvdgTG1XbZQwdDKrIm:b9nz0zs) ([raw file](https://github.com/Sp3EdeR/huroutes/blob/e3d07df3ce9410d90a7dae64b8b25d8906cafc54/index.html#L76)):*
> ```HTML
>       },
>       'themes': {
>         'System Theme': 'Rendszer színmód',
> ```

btw 'színmód' sounds strange

**Review by Sp3EdeR — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Sp3EdeR/huroutes/165)* status: all files reviewed, 4 unresolved discussions (waiting on @miklospuspan and @nbali)

*[a discussion](https://reviewable.io/reviews/Sp3EdeR/huroutes/165#-NZvbVe36127GsfobPRH:-NZwGeay0hW5gzJN0CJC:b-tjdx5a) (no related file):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

If I pick 'hungarian language' + 'műhold' + 'turistautak' at https://sp3eder.github.io/huroutes/pr/pr-165/ I get the tourist routes twice as the 'műhold' already has them (try toggle it on-off to see it easily) - although this is how the main branch behaves as well, I'm not sure this was intentional or not
</blockquote></details>

I know this, I could not solve it in a better way. I wanted to ensure that streets are visible on the sattelite view, to be able to tell what you're looking at. And I thought that the option of turistautak was useful for trip planning on all the other maps. This is how the two behaves. It might be possible to create a feature to auto-disable specific combinations of overlays, but I did not write that yet.

___
___
*[`index.html` line 76 at r1](https://reviewable.io/reviews/Sp3EdeR/huroutes/165#-NZvdgTG1XbZQwdDKrIl:-NZwDWHZ2hmgRsX2t-Gn:b-gixoa1) ([raw file](https://github.com/Sp3EdeR/huroutes/blob/e3d07df3ce9410d90a7dae64b8b25d8906cafc54/index.html#L76)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

btw 'színmód' sounds strange
</blockquote></details>

Have you got any other suggestions that are a better translation?
___
*[`index.html` line 80 at r1](https://reviewable.io/reviews/Sp3EdeR/huroutes/165#-NZvXnB41XT2NJp6qirI:-NZwDuJPBe-F02Xx3J4O:b-hecodp) ([raw file](https://github.com/Sp3EdeR/huroutes/blob/e3d07df3ce9410d90a7dae64b8b25d8906cafc54/index.html#L80)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

I only have a slight complaint about using the english version as keys as it will require changing them at multiple places even if just a character change in the english version
</blockquote></details>

I understand, but I wanted to do a very simple implementation at first run. It can be refactored if it ever poses an issue.
___
*[`index.html` line 98 at r1](https://reviewable.io/reviews/Sp3EdeR/huroutes/165#-NZvb0UHAjXmBI4I6k8C:-NZwEBqxBdMjd3bi6epd:bwsllpy) ([raw file](https://github.com/Sp3EdeR/huroutes/blob/e3d07df3ce9410d90a7dae64b8b25d8906cafc54/index.html#L98)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

I get that it was moved because it's a Hungarian overlay, but how come this requires the english name as the key, but the one above requires the localized name as key?
</blockquote></details>

The upper one has no English name, because it is a Hungarian brand. Due to this, it gets no display name vs. key name difference, both are the same. It is a user-togglable overlay layer. The lower one is a tileOverlay (automatically shown) for the Sattelite map. It displays a translucent road network on the sattelite imagery to make it better readable. So it must use the key name of the layer that it augments.
___
*[`res/huroutes.js` line 1143 at r1](https://reviewable.io/reviews/Sp3EdeR/huroutes/165#-NZvX5tY6g1l9Rg0navQ:-NZwFxW09CX9JpLYVBT2:beb4eio) ([raw file](https://github.com/Sp3EdeR/huroutes/blob/e3d07df3ce9410d90a7dae64b8b25d8906cafc54/res/huroutes.js#L1143)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

why don't you omit the conversion here if it's in huroutes.opt.... already like you do with the 2 other?
</blockquote></details>

The others are easy to check, so checking is a minor speed optimization. Checking this would probably not be any faster, since it needs to be split and tested each anyway. I thought it wasn't worth the additional coding.

**Review by nbali — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Sp3EdeR/huroutes/165)* status: all files reviewed, 2 unresolved discussions (waiting on @miklospuspan and @Sp3EdeR)

___
*[`index.html` line 76 at r1](https://reviewable.io/reviews/Sp3EdeR/huroutes/165#-NZvdgTG1XbZQwdDKrIl:-NZz0C4s1KgBZ3GulBkG:b-xlq9v6) ([raw file](https://github.com/Sp3EdeR/huroutes/blob/e3d07df3ce9410d90a7dae64b8b25d8906cafc54/index.html#L76)):*
<details><summary><i>Previously, Sp3EdeR (Speeder) wrote…</i></summary><blockquote>

Have you got any other suggestions that are a better translation?
</blockquote></details>

színséma, sötét mód? but i can live with this too
___
*[`index.html` line 98 at r1](https://reviewable.io/reviews/Sp3EdeR/huroutes/165#-NZvb0UHAjXmBI4I6k8C:-NZz0hxm2Ho6Bb3zLBXh:bknr3qx) ([raw file](https://github.com/Sp3EdeR/huroutes/blob/e3d07df3ce9410d90a7dae64b8b25d8906cafc54/index.html#L98)):*
<details><summary><i>Previously, Sp3EdeR (Speeder) wrote…</i></summary><blockquote>

The upper one has no English name, because it is a Hungarian brand. Due to this, it gets no display name vs. key name difference, both are the same. It is a user-togglable overlay layer. The lower one is a tileOverlay (automatically shown) for the Sattelite map. It displays a translucent road network on the sattelite imagery to make it better readable. So it must use the key name of the layer that it augments.
</blockquote></details>

so I should only see the 'tourist trips' in hungarian localization? I changed the language between hu and en and couldn't see differences in the pickable overlays


___
*[`res/huroutes.js` line 23 at r2](https://reviewable.io/reviews/Sp3EdeR/huroutes/165#-NZz1LXGADaA98bjqQl0:-NZz1LXH4X2lR1q-UmrO:bstba9y) ([raw file](https://github.com/Sp3EdeR/huroutes/blob/136210c3e1ed9746002bcefcae9b3d7808d69d47/res/huroutes.js#L23)):*
> ```JavaScript
>                 'Map': L.tileLayer.provider('OpenStreetMap',{className: 'tile-openstreetmap'}),
>                 'Terrain': L.tileLayer.provider('OpenTopoMap',{className: 'tile-opentopomap'}),
>                 'Sattelite': L.tileLayer.provider('Esri.WorldImagery',{className: 'tile-satellite'}),
> ```

a 'sattelite' remained

**Review by Sp3EdeR — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Sp3EdeR/huroutes/165)* status: all files reviewed, 2 unresolved discussions (waiting on @miklospuspan and @nbali)

___
*[`index.html` line 76 at r1](https://reviewable.io/reviews/Sp3EdeR/huroutes/165#-NZvdgTG1XbZQwdDKrIl:-NZz3V7k1pz92WMU3jZc:b-tp3b4d) ([raw file](https://github.com/Sp3EdeR/huroutes/blob/e3d07df3ce9410d90a7dae64b8b25d8906cafc54/index.html#L76)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

színséma, sötét mód? but i can live with this too
</blockquote></details>

Okay, then let's have it like this.
___
*[`index.html` line 98 at r1](https://reviewable.io/reviews/Sp3EdeR/huroutes/165#-NZvb0UHAjXmBI4I6k8C:-NZz3koY8ScnigKrvuTP:b-9n2e27) ([raw file](https://github.com/Sp3EdeR/huroutes/blob/e3d07df3ce9410d90a7dae64b8b25d8906cafc54/index.html#L98)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

so I should only see the 'tourist trips' in hungarian localization? I changed the language between hu and en and couldn't see differences in the pickable overlays



</blockquote></details>

Google Translate translates the entire page always, of course. But the Turistautak option only needs to exist for the Hungarian site. So if for example the Slovakians create skroutes, they won't need to translate Turistautak to Slovakian for their main site, since they won't have this option at all.

**Review by nbali — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Sp3EdeR/huroutes/165)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miklospuspan)

**Pull request merged**
